name: CD

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Generate Docs
        run: ./gradlew dokkaHtml
      - name: Install docs publisher
        run: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "dimitree54@gmail.com"
            git config user.name "Docs bot"
      - name: Deploy docs to gh-pages branch
        run: gh-pages --dist build/dokka/html
